Increment3
SakuraBurst/urlshortener pull request #3
Opened 2022-08-07 23:22 UTC by SakuraBurst

2022-08-09 13:06 UTC, kilchik requested changes

2022-08-09 13:06 UTC, kilchik commented on internal/app/api/api.go
> +	host.Path = "/" + id
У тебя здесь глобальная переменная, которую могут менять несколько горутин единовременно. Мне кажется, ты легко можешь избавиться от глобальной переменной и использовать локальную в данном месте

2022-08-09 13:06 UTC, kilchik commented on internal/controlers/urlshorter_controler.go
> +func GetURLFromID(id string) (*url.URL, error) {
Здорово, что заданы таймауты на чтение, но лучше дополнительно получать контекст в качестве аргумента в GetURLFromID(ctx context.Context...), а затем на базе него делать новый контекст с дополнительным таймаутом. Например context вызывающей функции уже может быть завершен, но ты об этом не узнаешь, поскольку сгенерировал таймаут из context.Background()

2022-08-09 13:06 UTC, kilchik commented on internal/repository/repository.go
> +	go getFromBd(urlChan, clh, id)
Каналы можно использовать для синхронизации обращения к ресурсу из несколько горутин, но такое решение оказывается сильно менее читаемым, нежели банальное решение на мьютексах.
На практике такие задачи проще и эффективнее (с точки зрения производительности) решать при помощи мьютексов

2022-08-10 13:28 UTC, SakuraBurst commented on internal/repository/repository.go
> +	go getFromBd(urlChan, clh, id)
Я посмотрел код и понял, что действительно можно сделать гораздо проще, не нужен никакой closedHelper, я могу передвать в горутину контекст и смотреть, валидный ли он до сих пор. Но что за банальное решение на мьютексах я так и не понял :(

2022-08-10 13:40 UTC, SakuraBurst commented
Мне интересно, почему ругнулся линтер, ведь я сначала читаю контекст пришедший из параметров для создания дочернего контекста, и только потом его перезаписываю в ту же переменную

2022-08-10 15:22 UTC, kilchik commented on internal/repository/repository.go
> +	go getFromBd(urlChan, clh, id)
Я имел в виду обезопасить обращение к `map[string]*url.URL`, сейчас у тебя идет обращение к этой структуре из разных горутин - могут возникать рейсы. Я думал, ты с помощью каналов пытался реализовать синхронизацию обращения к этой структуре.
В качестве рекомендаций по доработке
- стоит обезопасить обращение к `map[string]*url.URL` с помощью sync.Mutex
- я не вижу в данном контексте смысла в создании горутины для read/write, мне кажется, тут можно обойтись синхронным read/write без создания дополнительных горутин, ведь тебя нет блокирующей операции, для которой имеет смысл ожидать завершения context

2022-08-10 15:25 UTC, kilchik commented on internal/repository/repository.go
> +	go getFromBd(urlChan, clh, id)
По поводу линтера
В строке
`ctx, cancel := context.WithTimeout(context.Background(), time.Second*2)`
ты присваиваешь переменной ctx новое значение, игнорируя тот ctx, который тебе пришел в качестве аргумента функции.
Думаю, ты хотел сделать вот так
`ctx, cancel := context.WithTimeout(ctx, time.Second*2)`

2022-08-10 15:25 UTC, kilchik approved these changes

2022-08-10 22:31 UTC, merged